name: Run PHPUnit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu klonla
      uses: actions/checkout@v3

    - name: PHP kur
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Composer'ı yükle
      run: composer install

    - name: Testleri çalıştır
      run: composer test
